version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - '2181:2181'
    logging:
      driver: 'none'
    volumes:
      - ./kafka_container/zoo_data:/var/lib/zookeeper/data
      - ./kafka_container/zoo_log:/var/lib/zookeeper/log
  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - '9092:9092'
    environment:
      KAFKA_LISTENERS: 'INSIDE://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'INSIDE://kafka:29092,OUTSIDE://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_CREATE_TOPICS: 'noname.command-LOCAL:1:1, noname.event-LOCAL:1:1'
    depends_on:
      zookeeper:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "nc -z kafka 29092"]
      interval: 15s
      timeout: 10s
      retries: 5
    volumes:
      - ./kafka_container/broker_data:/var/lib/kafka/data
    logging:
      driver: 'none'
  